-- Neon's authenticated role needs table privileges before RLS policies apply.
-- drizzle-kit manages policies but not GRANTs, so they live here. DEFAULT
-- PRIVILEGES makes future tables in this schema inherit the same grants.
GRANT USAGE ON SCHEMA "public" TO "authenticated";--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "public" TO "authenticated";--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "authenticated";--> statement-breakpoint
ALTER TABLE "education" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "skill_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tailored_resumes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "work_experience" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "education" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select "education"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "education" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select "education"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "education" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select "education"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id()))) WITH CHECK ((select "education"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "education" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select "education"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "skill_categories" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select "skill_categories"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "skill_categories" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select "skill_categories"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "skill_categories" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select "skill_categories"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id()))) WITH CHECK ((select "skill_categories"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "skill_categories" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select "skill_categories"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "tailored_resumes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select "tailored_resumes"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "tailored_resumes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select "tailored_resumes"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "tailored_resumes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select "tailored_resumes"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id()))) WITH CHECK ((select "tailored_resumes"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "tailored_resumes" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select "tailored_resumes"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "tenants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.user_id() = "tenants"."clerk_user_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "tenants" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.user_id() = "tenants"."clerk_user_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "tenants" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.user_id() = "tenants"."clerk_user_id")) WITH CHECK ((select auth.user_id() = "tenants"."clerk_user_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "tenants" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.user_id() = "tenants"."clerk_user_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "user_profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select "user_profiles"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "user_profiles" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select "user_profiles"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "user_profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select "user_profiles"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id()))) WITH CHECK ((select "user_profiles"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "user_profiles" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select "user_profiles"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "work_experience" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select "work_experience"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "work_experience" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select "work_experience"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "work_experience" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select "work_experience"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id()))) WITH CHECK ((select "work_experience"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "work_experience" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select "work_experience"."tenant_id" = (select "tenants"."id" from "tenants" where "tenants"."clerk_user_id" = auth.user_id())));